# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nicobytes
logo: nicobytes
email: nicolas.molina.monroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador de software y organizador de comunidades, apasiado por javascript y front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicobytes.com" # the base hostname & protocol for your site
twitter: "https://twitter.com/nicobytes"

permalink: /:categories/:title

links:
  - title: Inicio
    url: /home
  - title: Blog
    url: /blog
  - title: Portafolio
    url: /portfolio
  - title: Contacto
    url: /contact

social:
  - link: "https://twitter.com/nicobytes"
    icon: "twitter"
  - link: "https://github.com/nicobytes"
    icon: "github"
  - link: "https://co.linkedin.com/in/nicobytes"
    icon: "linkedin"
  - link: "https://www.instagram.com/nicobytes/"
    icon: "instagram"
  - link: "https://angel.co/nicobytes"
    icon: "angellist"
  - link: "https://www.facebook.com/nicolas.molina.127"
    icon: "facebook"
  - link: "http://stackoverflow.com/users/6420164/nicolas-molina"
    icon: "stack-overflow"


# Build settings
markdown: kramdown
