# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nicobytes
logo: nicobytes
email: nicolas.molina.monroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador de software y organizador de comunidades, apasiado por javascript y front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicobytes.com" # the base hostname & protocol for your site
twitter: "https://twitter.com/nicobytes"

permalink: /:categories/:title

sass:
    style: compressed

links:
  - title: Home
    url: /
    target: '_self'
  - title: Blog
    url: 'http://www.ion-book.com/nicobytes/'
    target: '_blank'
  - title: Talks
    url: /talks
    target: '_self'

social:
  - link: "https://medium.com/@nicobytes"
    icon: "medium"
  - link: "https://twitter.com/nicobytes"
    icon: "twitter"
  - link: "https://github.com/nicobytes"
    icon: "github"
  - link: "https://co.linkedin.com/in/nicobytes"
    icon: "linkedin"
  - link: "https://www.instagram.com/nicobytes/"
    icon: "instagram"
  - link: "https://www.facebook.com/nicolas.molina.127"
    icon: "facebook"
  - link: "http://stackoverflow.com/users/6420164/nicolas-molina"
    icon: "stack-overflow"

talks:
  - title: "Firebase 3 + Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-11-11'
    location: 'Bogota, Colombia'
  - title: "AMP Project"
    type: 'conf'
    text: 'AMP Project es una tecnología de google para optimizar website enfocados a marketing de contenido.'
    slides: 'https://drive.google.com/open?id=1i8h9RyEtdVYqUChGz0YOJutjkAgquwVPVEPk0QfQCc0'
    image:
      url: 'images/time15.jpg'
      width: 1325
      height: 883
    date: '2016-06-13'
    location: 'Bogotá, Colombia'
  - title: "Introducción a Ionic 2"
    type: 'meetup'
    text: 'Todo lo que necesitas saber para comenzar en Ionic 2.'
    slides: 'http://www.nicobytes.com/ionic-v2-slides'
    image:
      url: 'images/time14.jpg'
      width: 2592
      height: 1936
    date: '2016-06-13'
    location: 'Bogotá, Colombia'
  - title: "Introducción a Ionic 2"
    type: 'youtube'
    text: 'Todo lo que necesitas saber para comenzar en Ionic 2.'
    slides: 'http://www.nicobytes.com/ionic-v2-slides'
    youtube: 'kWZcdgLbWQI'
    date: '2016-06-13'
    location: 'Viña del Mar, Chile'
  - title: "Curso de Ionic 1"
    type: 'course'
    text: 'Curso completo de ionic 1 para la <strong>Universidad Mayor de San Simon</strong>'
    image:
      url: 'images/time13.jpg'
      width: 960
      height: 540
    date: '2016-05-23'
    location: 'Cochabamba, Bolivia'
  - title: "FreelanceDay, Cochabamba"
    type: 'conf'
    text: 'Ven y conoce sobre las mejores prácticas para alcanzar tu potencial a nivel mundial, trabajar con las mejores empresas del mundo desde donde tu quieras, además descubre las tecnologías que están cambiando el mundo de la mano de los mejores..'
    slides: 'http://www.nicobytes.com/ionic-slides'
    image:
      url: 'images/time12.jpg'
      width: 960
      height: 540
    date: '2016-05-14'
    location: 'Cochabamba, Bolivia'
  - title: "FreelanceDay, La Paz"
    type: 'conf'
    text: 'Ven y conoce sobre las mejores prácticas para alcanzar tu potencial a nivel mundial, trabajar con las mejores empresas del mundo desde donde tu quieras, además descubre las tecnologías que están cambiando el mundo de la mano de los mejores..'
    slides: 'http://www.nicobytes.com/ionic-slides'
    image:
      url: 'images/time11.jpg'
      width: 1280
      height: 853
    date: '2016-05-07'
    location: 'La Paz, Bolivia'
  - title: "Ionic 1"
    type: 'workshop'
    text: 'Siguiendo con el workshop haremos una aplicación en live code, donde aprenderemos los principales componentes de ionic framework y su uso.'
    slides: 'http://slides.com/nicobytes/ionic-workshop'
    image:
      url: 'images/time10.jpg'
      width: 2048
      height: 1536
    date: '2016-04-30'
    location: 'Cochabamba, Bolivia'
  - title: "Ionic 1"
    type: 'workshop'
    text: 'Siguiendo con el workshop haremos una aplicación en live code, donde aprenderemos los principales componentes de ionic framework y su uso.'
    slides: 'http://slides.com/nicobytes/ionic-workshop'
    image:
      url: 'images/time9.jpg'
      width: 960
      height: 540
    date: '2016-04-16'
    location: 'Cochabamba, Bolivia'
  - title: "Ionic Cochabamba"
    type: 'meetup'
    text: 'Desarrollo de aplicaciones híbridas con ionic desarrollo multiplataforma con la misma base de código.'
    slides: 'http://www.nicobytes.com/ionic-slides'
    image:
      url: 'images/time8.jpg'
      width: 1280
      height: 768
    date: '2016-04-13'
    location: 'Cochabamba, Bolivia'
  - title: "Workshop: Ionic 1"
    type: 'workshop'
    text: 'Siguiendo con el workshop haremos una aplicación en live code, donde aprenderemos los principales componentes de ionic framework y su uso.'
    slides: 'http://slides.com/nicobytes/ionic-workshop'
    image:
      url: 'images/time7.jpg'
      width: 2048
      height: 1536
    date: '2016-04-09'
    location: 'La Paz, Bolivia'
  - title: "Conoce Ionic 2"
    type: 'youtube'
    text: 'En este hangout vamos a presentar la nueva versión del framework para el desarrollo de aplicaciones híbridas, Ionic. Es una excelente opción para el desarrollo de webapss que funcionan en todos los dispositivos. '
    slides: 'http://www.nicobytes.com/ionic-v2-slides'
    youtube: 'KgKo0BwHG34'
    date: '2016-04-05'
    location: 'La Paz, Bolivia'
  - title: "Ionic GDG La Paz"
    type: 'meetup'
    text: 'Desarrollo de aplicaciones híbridas con ionic desarrollo multiplataforma con la misma base de código.'
    slides: 'http://www.nicobytes.com/ionic-slides/'
    image:
      url: 'images/time6.jpg'
      width: 667
      height: 500
    date: '2016-03-24'
    location: 'La Paz, Bolivia'
  - title: "IonicDay"
    type: 'workshop'
    text: 'Siguiendo con el workshop haremos una aplicación en live code, donde aprenderemos los principales componentes de ionic framework y su uso.'
    image:
      url: 'images/time5.jpg'
      width: 960
      height: 720
    date: '2016-03-04'
    location: 'Lima, Peru'
  - title: "Apps con Ionic 1"
    type: 'meetup'
    text: 'Desarrollo de aplicaciones híbridas con ionic desarrollo multiplataforma con la misma base de código.'
    slides: 'http://www.nicobytes.com/ionic-slides/'
    image:
      url: 'images/time4.jpg'
      width: 960
      height: 540
    date: '2016-02-05'
    location: 'Ica, Peru'
  - title: "Pruebas unitarias en Angular 1.x"
    type: 'youtube'
    text: 'En este #devHangout conversamos acerca de Pruebas unitarias en Angular que empieza con la filosofia que es TDD. TDD es una práctica de ingeniería de software que involucra otras dos prácticas: Escribir las pruebas primero (Test First Development) y Refactorización (Refactoring).'
    slides: 'http://slides.com/nicobytes/testing'
    youtube: 'WNLM7ZX65e4'
    date: '2016-01-27'
    location: 'Ica, Peru'
  - title: "Ionic Framework"
    type: 'youtube'
    text: 'En este #devHangout conoceremos sobre el desarrollo de aplicaciones híbridas con ionic, el desarrollo multiplataforma con la misma base de código.'
    slides: 'http://www.nicobytes.com/ionic-slides/'
    youtube: 'z1V8Qxf_wL4'
    date: '2016-01-20'
    location: 'Ica, Peru'
  - title: "Haciendo apps con Ionic 1"
    type: 'meetup'
    text: 'Presentaremos a ionic framework y como ha cambiado la forma para desarrollar aplicaciones móviles híbridas, desde los componentes que maneja y su flujo de trabajo. Ionic en un framework basado en AngularJS con asombrosas API de UI/UX que mejoran el desarrollo. '
    slides: 'http://www.nicobytes.com/ionic-slides/'
    tweet: '664976174108512256'
    date: '2015-11-12'
    location: 'Bogotá, Colombia'
  - title: "Crosswalk Project"
    type: 'meetup'
    text: 'En un gran proyecto en cual puedes aumentar el performance de la aplicación híbrida, teniendo un webView más poderoso y estándar reduciendo la fragmentación de dispositivos, además veremos cómo añadirlos a proyectos con cordova, phonegap o ionic framework. '
    slides: 'http://slides.com/nicobytes/crosswalk#/'
    image:
      url: 'images/time2.jpg'
      width: 1280
      height: 720
    date: '2015-09-08'
    location: 'Bogotá, Colombia'
  - title: "Ionic 1 + Firebase"
    type: 'meetup'
    text: 'Aprende a trabajar con estas dos increíbles tecnologías para desarrollar tu aplicación móvil. Conocerás cómo integrar bases de datos NoSql con firebase, haciendo que tu aplicación tenga conexión en tiempo real con tus datos.'
    slides: 'http://slides.com/nicobytes/construyendo-apps#/'
    image:
      url: 'images/time1.jpeg'
      width: 1280
      height: 720
    date: '2015-07-09'
    location: 'Bogotá, Colombia'


# Build settings
markdown: kramdown
