# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nicobytes
logo: nicobytes
email: nicolas.molina.monroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador de software y organizador de comunidades, apasiado por javascript y front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicobytes.com" # the base hostname & protocol for your site
twitter: "https://twitter.com/nicobytes"

permalink: /:categories/:title

sass:
    style: compressed

links:
  - title: Inicio
    url: /
  - title: Blog
    url: 'http://www.ion-book.com/nicobytes/'
  - title: Charlas
    url: /talks

social:
  - link: "https://medium.com/@nicobytes"
    icon: "medium"
  - link: "https://twitter.com/nicobytes"
    icon: "twitter"
  - link: "https://github.com/nicobytes"
    icon: "github"
  - link: "https://co.linkedin.com/in/nicobytes"
    icon: "linkedin"
  - link: "https://www.instagram.com/nicobytes/"
    icon: "instagram"
  - link: "https://www.facebook.com/nicolas.molina.127"
    icon: "facebook"
  - link: "http://stackoverflow.com/users/6420164/nicolas-molina"
    icon: "stack-overflow"

talks:
  - title: "Firebase 3 + Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-11-11'
    place: 'Capital Junior College'
    location: 'Bogota, Colombia'
  - title: "Ecmascript 6 + Typescript + Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-11-11'
    place: 'Capital Junior College'
    location: 'Bogota, Colombia'
  - title: "Introducción a Ionic2 & Angular2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-09-15'
    place: 'Capital Junior College'
    location: 'Cali, Colombia'
  - title: "Introducción a Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-09-09'
    place: 'Capital Junior College'
    location: 'Medellin, Colombia'
  - title: "Ionic 2 VS Native Script VS React Native"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-08-19'
    place: 'Capital Junior College'
    location: 'Medellin, Colombia'
  - title: "Crosswalk-project"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-07-13'
    place: 'Capital Junior College'
    location: 'Medellin, Colombia'
  - title: "Introducción a Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-07-13'
    place: 'Capital Junior College'
    location: 'Medellin, Colombia'
  - title: "Ionic Cbba"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-05-13'
    place: 'Elemental'
    location: 'Cochabamba, Bolivia'
  - title: "Ionic Workshop"
    type: 'workshop'
    slides: ''
    cover: ''
    date: '2016-04-09'
    place: 'Elemental'
    location: 'La Paz, Bolivia'
  - title: "Ionic GDG La Paz"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-03-25'
    place: 'Elemental'
    location: 'La Paz, Bolivia'
  - title: "IonicDay"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-02-27'
    place: 'DevAcademy'
    location: 'Lima, Peru'
  - title: "Apps con Ionic "
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-02-05'
    place: 'DevAcademy'
    location: 'Ica, Peru'
  - title: "Pruebas unitarias en Angular "
    type: 'hangout'
    slides: ''
    cover: ''
    date: '2016-01-27'
    place: 'DevAcademy'
    location: 'Ica, Peru'
  - title: "Ionic Framework"
    type: 'hangout'
    slides: ''
    cover: ''
    date: '2016-01-20'
    place: 'DevAcademy'
    location: 'Ica, Peru'
  - title: "Crosswalk-project"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2015-09-08'
    place: 'ViveLab'
    location: 'Bogotá, Colombia'
  - title: "Ionic + Firebase"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2015-07-09'
    place: 'ViveLab'
    location: 'Bogotá, Colombia'


# Build settings
markdown: kramdown
