# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nicobytes
logo: nicobytes
email: nicolas.molina.monroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador de software y organizador de comunidades, apasiado por javascript y front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicobytes.com" # the base hostname & protocol for your site
twitter: "https://twitter.com/nicobytes"

permalink: /:categories/:title

sass:
    style: compressed

links:
  - title: Home
    url: /
    target: '_self'
  - title: Blog
    url: 'http://www.ion-book.com/nicobytes/'
    target: '_blank'
  - title: Talks
    url: /talks
    target: '_self'

social:
  - link: "https://medium.com/@nicobytes"
    icon: "medium"
  - link: "https://twitter.com/nicobytes"
    icon: "twitter"
  - link: "https://github.com/nicobytes"
    icon: "github"
  - link: "https://co.linkedin.com/in/nicobytes"
    icon: "linkedin"
  - link: "https://www.instagram.com/nicobytes/"
    icon: "instagram"
  - link: "https://www.facebook.com/nicolas.molina.127"
    icon: "facebook"
  - link: "http://stackoverflow.com/users/6420164/nicolas-molina"
    icon: "stack-overflow"

talks:
  - title: "Firebase 3 + Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-11-11'
    location: 'Bogota, Colombia'
  - title: "Ecmascript 6 + Typescript + Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-11-11'
    location: 'Bogota, Colombia'
  - title: "Introducción a Ionic2 & Angular2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-09-15'
    location: 'Cali, Colombia'
  - title: "Introducción a Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-09-09'
    location: 'Medellin, Colombia'
  - title: "Ionic 2 VS Native Script VS React Native"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-08-19'
    location: 'Medellin, Colombia'
  - title: "Crosswalk-project"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-07-13'
    location: 'Medellin, Colombia'
  - title: "Introducción a Ionic 2"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-07-13'
    location: 'Medellin, Colombia'
  - title: "Ionic Cbba"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-05-13'
    location: 'Cochabamba, Bolivia'
  - title: "Ionic Workshop"
    type: 'workshop'
    slides: ''
    cover: ''
    date: '2016-04-09'
    location: 'La Paz, Bolivia'
  - title: "Ionic GDG La Paz"
    type: 'meetup'
    slides: ''
    cover: ''
    date: '2016-03-25'
    location: 'La Paz, Bolivia'
  - title: "IonicDay"
    type: 'workshop'
    text: 'Siguiendo con el workshop haremos una aplicación en live code, donde aprenderemos los principales componentes de ionic framework y su uso.'
    image:
      url: 'images/time5.jpg'
      width: 960
      height: 720
    date: '2016-03-04'
    location: 'Lima, Peru'
  - title: "Apps con Ionic 1"
    type: 'meetup'
    text: 'Desarrollo de aplicaciones híbridas con ionic desarrollo multiplataforma con la misma base de código.'
    slides: 'http://www.nicobytes.com/ionic-slides/'
    image:
      url: 'images/time4.jpg'
      width: 960
      height: 540
    date: '2016-02-05'
    location: 'Ica, Peru'
  - title: "Pruebas unitarias en Angular 1.x"
    type: 'youtube'
    text: 'En este #devHangout conversamos acerca de Pruebas unitarias en Angular que empieza con la filosofia que es TDD. TDD es una práctica de ingeniería de software que involucra otras dos prácticas: Escribir las pruebas primero (Test First Development) y Refactorización (Refactoring).'
    slides: 'http://slides.com/nicobytes/testing'
    youtube: 'WNLM7ZX65e4'
    date: '2016-01-27'
    location: 'Ica, Peru'
  - title: "Ionic Framework"
    type: 'youtube'
    text: 'En este #devHangout conoceremos sobre el desarrollo de aplicaciones híbridas con ionic, el desarrollo multiplataforma con la misma base de código.'
    slides: 'http://www.nicobytes.com/ionic-slides/'
    youtube: 'z1V8Qxf_wL4'
    date: '2016-01-20'
    location: 'Ica, Peru'
  - title: "Haciendo apps con Ionic 1"
    type: 'meetup'
    text: 'Presentaremos a ionic framework y como ha cambiado la forma para desarrollar aplicaciones móviles híbridas, desde los componentes que maneja y su flujo de trabajo. Ionic en un framework basado en AngularJS con asombrosas API de UI/UX que mejoran el desarrollo. '
    slides: 'http://www.nicobytes.com/ionic-slides/'
    tweet: '664976174108512256'
    date: '2015-11-12'
    location: 'Bogotá, Colombia'
  - title: "Crosswalk Project"
    type: 'meetup'
    text: 'En un gran proyecto en cual puedes aumentar el performance de la aplicación híbrida, teniendo un webView más poderoso y estándar reduciendo la fragmentación de dispositivos, además veremos cómo añadirlos a proyectos con cordova, phonegap o ionic framework. '
    slides: 'http://slides.com/nicobytes/crosswalk#/'
    image:
      url: 'images/time2.jpg'
      width: 1280
      height: 720
    date: '2015-09-08'
    location: 'Bogotá, Colombia'
  - title: "Ionic 1 + Firebase"
    type: 'meetup'
    text: 'Aprende a trabajar con estas dos increíbles tecnologías para desarrollar tu aplicación móvil. Conocerás cómo integrar bases de datos NoSql con firebase, haciendo que tu aplicación tenga conexión en tiempo real con tus datos.'
    slides: 'http://slides.com/nicobytes/construyendo-apps#/'
    image:
      url: 'images/time1.jpeg'
      width: 1280
      height: 720
    date: '2015-07-09'
    location: 'Bogotá, Colombia'


# Build settings
markdown: kramdown
